name: Run Tests
on:
  - push
  - pull_request
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - uses: actions/setup-python@v5
        with:
          python-version: '>=3.9'
      - uses: actions/checkout@v4
      - run: |
          npm install
          npm run init
          npm test
